apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ksm-codeready-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: codeready.rules
      rules:
        - alert: CodeReadyPodCount
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: Pod count for namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} printf "%.0f" $value {{ "}}" }}. Expected at least 2 pods.
          expr: |
            (1-absent(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"})) or sum(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"}) < 2
          for: 5m
          labels:
            severity: critical