apiVersion: applicationmonitoring.integreatly.org/v1alpha1
kind: BlackboxTarget
metadata:
  name: {{ index .Params "name"  }}
  namespace: {{ index .Params "Namespace" }}
  labels:
    monitoring-key: {{ index .Params "MonitoringKey" }}
spec:
  blackboxTargets:
    - service: {{ index .Params "service"  }}
      url: {{ index .Params "url" }}
      module: {{ index .Params "module" }}